---
ID: "65aa2e36-b31b-4927-8e6d-81173f26d4e0"
Parent: "fc595fcd-6938-4ac3-a075-83983d8aa96d"
Template: "71496766-f5a0-437a-8375-4d44d5f39a0e"
Path: "/sitecore/content/nutrilife-innovations/careers/Home/Life at NutriLife/Environment and Sustainability"
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{1CB19D25-1836-4122-9731-1C23D313B440}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240816T202609Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Environment and Sustainability
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "39df41f5-8228-40f5-9277-62822da2d0c0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\justin.vogt@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240816T202609Z
    - ID: "e0483b1c-9d99-4824-9b74-b3373289b9bd"
      Hint: Title
      Value: Environment and Sustainability
