---
ID: "5fc5759e-9007-4889-8d01-1af62ee0d9a3"
Parent: "b5ee7385-a10b-4a0a-a45b-decae4a0aa86"
Template: "b5ee7385-a10b-4a0a-a45b-decae4a0aa86"
Path: "/sitecore/templates/Project/nutri-kids/Page Designs/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {829FC742-09D4-4981-A0AA-04C055BE5661}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240813T215250Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\justin.vogt@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\justin.vogt@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8d29d9e5-3f93-4afd-98e6-a5f2956f3f06"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\justin.vogt@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240813T215251Z
